### ISSUE TITLE
CORS  , when deploy it

### ISSUE THREAD

**Issue by Jiangjao** [BioAnalyticResource/eFP-Seq_Browser#6]
**Describe the bug**
how to solve CORS  ? when I deploy it on my remote host.

**To Reproduce**
```text
# env
1. Linux VM-8-15-ubuntu 4.15.0-159-generic
2. apache 2.4
3. apache allow all    Access-Control-Allow-Origin
```

1. Go to click `load data` button
2. See error:
```text
ERROR IN get_gene_structures !

PLEASE REFRESH PAGE, RELOAD OR RE-INPUT DATA OR TRY AGAIN AT A LATER TIME
```
![网页捕获_3-6-2022_104334_42 193 172 132](https://user-images.githubusercontent.com/27748764/171776532-0891fd0f-182e-457d-b58e-bf2d86581f3b.jpeg)

**Expected behavior**
load the data_set and display on the web page

**Screenshots**

**Desktop (please complete the following information):**

-   Browser [e.g. chrome, edge]
-   Version [latest]

**Additional context**
the browser console
```text
Access to XMLHttpRequest at 'https://bar.utoronto.ca/webservices/bar_araport/gene_structure_by_locus.php?locus=AT2G24270' from origin 'http://myremotehost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Error in logic: ERROR IN get_gene_structures !
```

**Comment by AlexJSully** [comment]
Hi @Jiangjao ! Apologies for the very late reply to this issue. We just updated the eFP-Seq Browser with [[enhancement][bug fix][docs] Able to run the eFP-Seq Browser locally #21 ](https://github.com/BioAnalyticResource/eFP-Seq_Browser/pull/21) which includes instructions in the [README](https://github.com/BioAnalyticResource/eFP-Seq_Browser/blob/master/README.md) on how to run the eFP-Seq Browser locally on your PC. 

I hope this helps and feel free to ping us if you have any further issues!
